<a href="https://colab.research.google.com/github/vanviethieuanh/CS114.L21/blob/main/Predict_runtime_with_data_magnitude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Predict_runtime_with_data_magnitude/data2.csv')
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Predict_runtime_with_data_magnitude/data3.csv')

In [4]:
import numpy as np
x_train = np.array(df_train['Size']).reshape(-1, 1)
y_train = np.array(df_train['Time'])
x_test = np.array(df_test['Size']).reshape(-1, 1)
y_test = np.array(df_test['Time'])
print('Train dataset:')
print(x_train)
print(y_train)
print('Test dataset:')
print(x_test)
print(y_test)

Train dataset:
[[6083695]
 [1954367]
 [3734185]
 ...
 [9837364]
 [9466593]
 [4080801]]
[0.521842 0.152648 0.298548 ... 0.801394 0.776407 0.314468]
Test dataset:
[[37837612]
 [37395246]
 [36610827]
 ...
 [33520323]
 [21243264]
 [21380484]]
[4.12166 3.92089 3.2154  ... 2.90918 1.80292 1.82795]


In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(x_train,y_train)

In [9]:
from sklearn.metrics import mean_squared_error
import math
print('mean squared error with training dataset: ')
print(math.sqrt(mean_squared_error(y_train, lr.predict(x_train))))
print('mean squared error with testing dataset: ')
print(math.sqrt(mean_squared_error(y_test, lr.predict(x_test))))

mean squared error with training dataset: 
0.011974025522667318
mean squared error with testing dataset: 
0.14375308482794058
